name: jobsense
description: Job search platform
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  amplify_api: ^0.6.14
  amplify_auth_cognito: ^0.6.14
  amplify_authenticator: ^0.2.5
  amplify_flutter: ^0.6.14
  animated_text_kit: ^4.2.2
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cloud_firestore: ^4.15.4
  equatable: ^2.0.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.4
  fireflutter: ^0.3.3
  flex_seed_scheme: ^1.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.6.1
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  glass_kit: ^3.0.0
  heroicons: ^0.9.0
  hydrated_bloc: ^9.1.3
  intl: ^0.18.0
  path_provider: ^2.1.2
  quickalert: ^1.0.2
  uuid: ^3.0.6

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

flutter_assets:
  assets_path: assets/
  output_path: lib/src/app/
  filename: assets.dart